name: Run dsa-cli Validation

on:
  pull_request:
    paths:
      - 'DSA/**'

jobs:
  cli-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g @dsa/cli
      - run: dsa-cli validate DSA/
